Foreground true
TCPSocket 3310
TCPAddr 0.0.0.0
DatabaseDirectory /var/lib/clamav
MaxFileSize 20M
MaxScanSize 20M
StreamMaxLength 20M
MaxThreads 4
ReadTimeout 60
CommandReadTimeout 15
LogTime true
LogClean false
User clamav
